#!/bin/sh
set -e

command=$1
dotfiles_dir="$HOME/dotfiles"

. util

if [ -e $dotfiles_dir/.git ]; then
  cd $dotfiles_dir && git pull
else
  git clone https://github.com/danielefongo/dotfiles.git $dotfiles_dir
  cd $dotfiles_dir
fi

# dots
if [[ $command == "all" ]] || [[ $command == "dots" ]]; then
  print_title "linking dot-files"

  for file in `echo dots/.*`
  do
    if [ -f "$file" ]; then
      filename=$(basename "$file")

      echo "----> linking $filename"

      if [ -f "$HOME/$filename" ]; then
        rm ~/$filename
      fi

      ln -sf ~/dotfiles/$file ~/$filename
    fi
  done
fi

# scripts
if [[ $command == "all" ]] || [[ $command == "scripts" ]]; then
  print_title "installing scripts"

  chmod +x scripts/*

  for file in `echo scripts/* | sort`
  do
    echo "--> executing $file"

    . $file
  done
fi
