#!/bin/bash

FONTS_DIR="$HOME/Library/Fonts/"

echo
if [ -d "$FONTS_DIR/FiraCode" ]; then
  rm -r "$FONTS_DIR/FiraCode"
fi
wget -q https://github.com/tonsky/FiraCode/releases/download/1.206/FiraCode_1.206.zip -O "$FONTS_DIR/FiraCode.zip"
unzip "$FONTS_DIR/FiraCode" "ttf/*" -d "$FONTS_DIR" 1>/dev/null
rm "$FONTS_DIR/FiraCode.zip"
mv "$FONTS_DIR/ttf" "$FONTS_DIR/FiraCode"
