#!/bin/bash

if ! type "brew" > /dev/null; then
  echo ".... brew install"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo ".... updating brew"
brew update && brew upgrade && brew cleanup

if ! type "git" > /dev/null; then
  echo ".... installing git"
  brew install git
fi

echo ".... installing tig"
brew install tig

echo ".... installing diff-so-fancy"
brew install diff-so-fancy
