#!/bin/bash

# iterm2
cask_install iterm2
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$HOME/dotfiles/dots/.extra-dots/iterm2"

if ! type "zsh" > /dev/null; then
  echo ".... installing zsh"
  cd ~
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  chsh -s $(which zsh) $(whoami)
  source ~/.bash_profile 2>/dev/null
  source ~/.zshrc 2/dev/null
fi

# git
if ! type "git" > /dev/null; then
  brew_install git
fi

# tig
brew_install tig

# diff-so-fancy
brew_install diff-so-fancy

# autojump
brew_install autojump

# git-extras
brew_install git-extras

# wget
brew_install wget

# the_silver_searcher
brew_install the_silver_searcher

# tree
brew_install tree

# bat
brew_install bat
