#!/bin/bash


# Sublime Text 3
SUBLIME_SETTINGS_PATH=/Users/$(whoami)/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
SUBLIME_PACKAGES_PATH=/Users/$(whoami)/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages
DOTFILE_SETTINGS_PATH=/Users/$(whoami)/.extra-dots/sublime

brew cask install sublime-text
wget -q https://packagecontrol.io/Package%20Control.sublime-package -O "$SUBLIME_PACKAGES_PATH/Package Control.sublime-package"
rm "$SUBLIME_SETTINGS_PATH/Preferences.sublime-settings" "$SUBLIME_SETTINGS_PATH/Package Control.sublime-settings" 2>/dev/null
ln -s "$DOTFILE_SETTINGS_PATH/Preferences.sublime-settings" "$SUBLIME_SETTINGS_PATH/Preferences.sublime-settings"
ln -s "$DOTFILE_SETTINGS_PATH/Package Control.sublime-settings" "$SUBLIME_SETTINGS_PATH/Package Control.sublime-settings"
