#!/bin/bash

if ! type "brew" > /dev/null; then
  echo ".... brew install"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# wget
brew_install wget

echo ".... updating brew"
brew update && brew upgrade && brew cleanup
