#!/bin/bash

# dozer
cask_install dozer

# flux
cask_install flux
defaults write org.herf.Flux dayColorTemp 5800
defaults write org.herf.Flux nightColorTemp 3800
defaults write org.herf.Flux lateColorTemp 2700
