#!/bin/bash

# iterm2
cask_install iterm2
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$HOME/dotfiles/conf/dots/iterm2"

# zsh
brew_install zsh
sudo chsh -s $(which zsh) $(whoami)

# antigen
brew_install antigen

# git
if ! type "git" > /dev/null; then
  brew_install git
fi

# tig
brew_install tig

# diff-so-fancy
brew_install diff-so-fancy

# autojump
brew_install autojump

# git-extras
brew_install git-extras

# the_silver_searcher
brew_install the_silver_searcher

# tree
brew_install tree

# bat
brew_install bat

# tldr
brew_install tldr

# rmtrash
brew_install rmtrash
